### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ghost** [deech/fltkc#1]
Hi, I got this compilation error when I'm trying to build the binding

```
*** Compiling Fl_Tree_ItemC.cpp...
In file included from Fl_Tree_ItemC.h:8:0,
                 from Fl_Tree_ItemC.cpp:1:
/usr/include/FL/Fl_Tree_Item.H: In function ‘int Fl_Tree_Item_calc_item_height(fl_Tree_Item, fl_Tree_Prefs)’:
/usr/include/FL/Fl_Tree_Item.H:118:7: error: ‘int Fl_Tree_Item::calc_item_height(const Fl_Tree_Prefs&) const’ is protected
   int calc_item_height(const Fl_Tree_Prefs &prefs) const;
       ^
Fl_Tree_ItemC.cpp:30:107: error: within this context
 ee_Item*>(tree_item))->calc_item_height(*(static_cast<Fl_Tree_Prefs*>(prefs)));
                                                                              ^
Makefile:99: recipe for target 'Fl_Tree_ItemC.o' failed
make[1]: *** [Fl_Tree_ItemC.o] Error 1
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by deech** [comment]
Which version of `fltk` do you have installed? You can check this by doing `fltk-config --version`, if you have a version that isn't `1.3.4` please upgrade. Also just in case you installed `fltk` from a package manager, I've found them all pretty unreliable, the best way to get going is `stack build --flag fltkhs:bundled`.
Thanks for the report!

**Comment by deech** [comment]
Oh wait, I just realized you opened this issue on the `fltkc` repo and not `fltkhs`. This project been abandoned and incorporated into `fltkhs`. Sorry.

**Comment by ghost** [comment]
Ah nevermind. I'll close this issue. The C code in the fltkhs does work.
